//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightsElem
    {
        public int Id { get; set; }
        public bool IsUser { get; set; }
        public bool AssemblySelf { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual User User { get; set; }
        public virtual Parachute Parachute { get; set; }
    }
}
