//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            this.Altitude = 4000;
            this.FlightsElem = new HashSet<FlightsElem>();
        }
    
        public int Id { get; set; }
        public System.DateTime FlyDateTime { get; set; }
        public string FlyNr { get; set; }
        public short FlyStatus { get; set; }
        public int Altitude { get; set; }
    
        public virtual Airplane Airplane { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightsElem> FlightsElem { get; set; }
    }
}
