//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightsElem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlightsElem()
        {
            this.AssemblySelf = false;
            this.TeamName = "Null";
        }
    
        public int Id { get; set; }
        public Nullable<bool> AssemblySelf { get; set; }
        public Nullable<int> Lp { get; set; }
        public string TeamName { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual User User { get; set; }
        public virtual Parachute Parachute { get; set; }
    }
}
