//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public decimal Value { get; set; }
        public Nullable<decimal> Count { get; set; }
        public Nullable<bool> IsBooked { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual PaymentsSetting PaymentsSetting { get; set; }
        public virtual User User { get; set; }
        public virtual FlightsElem FlightsElem { get; set; }
    }
}
