//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyReg.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkyReg.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @result bit = 0
        ///
        ///IF db_id(&apos;DataBaseName&apos;) IS NOT NULL
        ///BEGIN
        ///	set @result = 0
        ///END
        ///ELSE
        ///BEGIN
        ///	CREATE DATABASE DataBaseName
        ///	set @result = 1
        ///END
        ///
        ///SELECT @Result.
        /// </summary>
        internal static string Create_DataBase {
            get {
                return ResourceManager.GetString("Create_DataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///-- --------------------------------------------------
        ///-- Entity Designer DDL Script for SQL Server 2005, 2008, 2012 and Azure
        ///-- --------------------------------------------------
        ///-- Date Created: 06/15/2017 20:03:10
        ///-- Generated from EDMX file: F:\Projekty 2017\Repozytorium2\SkyReg_Dev\SkyReg\DataLayer\DLModel.edmx
        ///-- --------------------------------------------------
        ///
        ///SET QUOTED_IDENTIFIER OFF;
        ///GO
        ///USE [SkyRegDB];
        ///GO
        ///IF SCHEMA_ID(N&apos;dbo&apos;) IS NULL EXECUTE(N&apos;CREATE SCHEMA [dbo]&apos;);
        ///GO
        ///
        ///-- ----- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DLModel_edmx {
            get {
                return ResourceManager.GetString("DLModel_edmx", resourceCulture);
            }
        }
    }
}
